"""Schemas for triplet generation pipeline."""

from datetime import datetime
from typing import List, Optional

from pydantic import BaseModel, Field


class GeneratedStatement(BaseModel):
    """A statement generated by an LLM role-playing as a persona."""

    statement_id: str = Field(..., description="Unique statement identifier")
    persona_id: str = Field(..., description="ID of the persona who 'wrote' this statement")
    issue_id: str = Field(..., description="ID of the issue this statement addresses")
    text: str = Field(..., description="The generated statement text")
    model: str = Field(..., description="Model used for generation")
    timestamp: datetime = Field(default_factory=datetime.now)


class Ranking(BaseModel):
    """A persona's ranking of statements on an issue."""

    ranking_id: str = Field(..., description="Unique ranking identifier")
    persona_id: str = Field(..., description="ID of the persona doing the ranking")
    issue_id: str = Field(..., description="ID of the issue being ranked")
    ranked_statement_ids: List[str] = Field(
        ..., description="Statement IDs ordered from most to least preferred"
    )
    model: str = Field(..., description="Model used for generation")
    timestamp: datetime = Field(default_factory=datetime.now)


class Triplet(BaseModel):
    """A preference triplet for contrastive learning."""

    anchor_text: str = Field(..., description="Anchor text (persona's own ideal statement)")
    pos_text: str = Field(..., description="Positive text (higher ranked statement)")
    neg_text: str = Field(..., description="Negative text (lower ranked statement)")

    # Legacy fields (optional for backward compatibility)
    anchor_persona_id: Optional[str] = Field(None, description="ID of the anchor persona")
    issue_id: Optional[str] = Field(None, description="ID of the issue")
    pos_statement_id: Optional[str] = Field(None, description="ID of the positive statement")
    neg_statement_id: Optional[str] = Field(None, description="ID of the negative statement")

    # Cross-topic triplet fields
    anchor_issue_id: Optional[str] = Field(None, description="ID of the anchor's issue")
    pos_issue_id: Optional[str] = Field(None, description="ID of the positive's issue")
    neg_issue_id: Optional[str] = Field(None, description="ID of the negative's issue")
    triplet_type: Optional[str] = Field(None, description="Type: cross_topic or within_topic")
    difficulty: Optional[str] = Field(None, description="Difficulty level")

    class Config:
        extra = "allow"  # Allow extra fields


class GenerationMetadata(BaseModel):
    """Metadata about a generation run."""

    version: str = Field("1.0.0", description="Schema version")
    created_at: datetime = Field(default_factory=datetime.now)
    n_issues: int = Field(..., description="Number of issues processed")
    personas_per_issue: int = Field(..., description="Number of personas per issue")
    model: str = Field(..., description="Model used for generation")
    seed: int = Field(..., description="Random seed used")
    statement_count: int = Field(0, description="Total statements generated")
    ranking_count: int = Field(0, description="Total rankings generated")
    triplet_count: int = Field(0, description="Total triplets generated")
